snippets:
  - name: "Load Switchboard Program"
    description: ""
    filename: "load-program.ts"
  - name: "Create a Queue"
    description: ""
    filename: "create-queue.ts"
  - name: "Create a Data Feed"
    description: ""
    filename: "create-feed.ts"
  - name: "Create a Job"
    description: ""
    filename: "create-job.ts"
  - name: "Add Job to Data Feed"
    description: ""
    filename: "add-job.ts"
  - name: "Create Feed Permissions"
    description: ""
    filename: "create-feed-permissions.ts"
  - name: "Set Feed Permissions"
    description: ""
    filename: "set-feed-permissions.ts"
  - name: "Add Feed to Crank"
    description: ""
    filename: "add-feed-to-crank.ts"
  - name: "Request a Feed Update"
    description: ""
    filename: "request-feed-update.ts"
