name: Test @switchboard-xyz/near.js
on:
  workflow_dispatch:
  pull_request:
    branches: [main]

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    name: "Build and Test JS SDK"
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7.28.0

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "pnpm"

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install Dependencies
        working-directory: javascript/near.js
        run: pnpm install --frozen-lockfile

      - name: Build
        working-directory: javascript/near.js
        run: pnpm build

      - name: Test
        working-directory: javascript/near.js
        run: pnpm test

      # - name: Install Node.js
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: 18
      #     cache: "pnpm"

      # - name: Publish
      #   if:
      #     github.event_name == 'workflow_dispatch' || (github.ref ==
      #     'refs/heads/main' && github.event_name != 'pull_request')
      #   run: pnpm publish-packages
      #   env:
      #     GH_TOKEN: ${{ secrets.GH_TOKEN }}
      #     NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
